logging.level.org.zalando.logbook: TRACE

spring.datasource.url=jdbc:h2:file:D:/java-filmorate/java-filmorate/db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password


spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.schema-locations=classpath:schema.sql
spring.test.database.replace=NONE


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


logging.level.org.springframework.jdbc=DEBUG

